# Generated by Django 6.0.4 on 2026-05-23 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'A faire'), ('EN_COURS', 'En cours'), ('En_REVISION', 'En revision'), ('TERMINE', 'Termine')], default='A_FAIRE', max_length=20)),
                ('priorite', models.CharField(choices=[('BAS', 'Bas'), ('MOYEN', 'Moyen'), ('ELEVE', 'Eleve'), ('URGENT', 'Urgent')], default='MOYEN', max_length=20)),
                ('progression', models.IntegerField(default=0)),
                ('date_fermeture', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('assignation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_crees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projets.projet')),
            ],
        ),
    ]
