# Generated by Django 6.0.4 on 2026-05-23 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece_Jointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pieces_jointes/')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('date_televersement', models.DateTimeField(auto_now_add=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='taches.tache')),
                ('televerse_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
