# Generated by Django 6.0.4 on 2026-05-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('PROGRAMMATION', 'Programmation'), ('ACTIF', 'Actif'), ('EN_ATTENTE', 'En attente'), ('COMPLETE', 'Complete'), ('ANNULE', 'Annule')], default='PROGRAMMATION', max_length=20),
        ),
    ]
