# Generated by Django 6.0.4 on 2026-05-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_alter_projet_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='progression',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membreprojet',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur'), ('CHEF_PROJET', 'Chef Projet'), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=20),
        ),
    ]
