# Generated by Django 6.0.4 on 2026-05-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='est_lu',
            new_name='est_lue',
        ),
    ]
